name: south_africa_selenium
'on':
  schedule:
    - cron: 0 22 * * *
  workflow_dispatch: # 添加一个可以手动运行的按钮
jobs:
  south_africa_selenium_bot:
    runs-on: windows-latest
    steps:
      - name: check_code
        uses: actions/checkout@master
      - name: set up Python 3.8
        uses: actions/setup-Python@v2
        with:
          python-version: '3.8'
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install selenium
          pip install webdriver-manager
      - name: process data
        run: python ./code/africa/south_africa_workflow.py
      - name: commit and push if it changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          find ./ -name ".pyc"　|xargs rm -rf
          git add -A
          timestamp=$(date -u)
          git commit -m "Last updated on: ${timestamp}" || exit 0
          git push
